FROM node:20-slim
RUN apt-get update -y && apt-get install -y openssl
WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install

COPY . .

# Generate prisma client before starting
RUN npx prisma generate

EXPOSE 3000

CMD ["npm", "run", "dev"]
